---
name: Release

on:
  push:
  workflow_dispatch:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v16

      - name: Run goreleaser
        run: nix develop --command -- goreleaser build --single-target --snapshot
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: dist/